"""new_tags

Revision ID: 41ff27845516
Revises: 2079c65aaf2c
Create Date: 2015-08-02 21:39:34.635890

"""

# revision identifiers, used by Alembic.
revision = '41ff27845516'
down_revision = '2079c65aaf2c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
